### ISSUE TITLE
Infinite loop when encountering nested primitive type aliases

### ISSUE THREAD

**Issue by nefilim** [json4s/json4s#169] opened 2014-11-26 17:59 UTC
Related or similar to #76 - hard to believe that's still not addressed!

Using 3.2.11 on scala 2.10.4, serializing this works:

```
case class Test(map: Map[Int, String]) 
```

but serializing this does not:

```
type ID = Int
case class Test(map: Map[ID, String])
```

a thread dump shows:

```
   java.lang.Thread.State: RUNNABLE
	at org.json4s.reflect.ScalaSigReader$.findPrimitive$3(ScalaSigReader.scala:121)
	at org.json4s.reflect.ScalaSigReader$.findArgTypeForField(ScalaSigReader.scala:117)
	at org.json4s.reflect.ScalaSigReader$.readField(ScalaSigReader.scala:38)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:66)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$3.apply(Reflector.scala:65)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.fields(Reflector.scala:65)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.properties(Reflector.scala:82)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:158)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:50)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:44)
	at org.json4s.reflect.package$Memo.apply(package.scala:39)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:44)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:90)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:196)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:67)
	at org.json4s.native.Serialization$.write(Serialization.scala:43)
	at org.json4s.native.Serialization$.write(Serialization.scala:37)
```

**Comment by jeffdc** [comment] 2015-02-12 04:54
I could only repeat this if I did not define the case class in a top level object. i.e.,
```scala
object LittleBunnyFooFoo {
  type ID = Int

  def main(args: Array[String]) {
    case class Foo(is: List[ID])
    val f = Foo(10 :: Nil)

    implicit lazy val formats = DefaultFormats

    println(Extraction.decompose(f).extract[Foo])
  }
}
```
fails, but interestingly does not lead to an infinite loop. Instead I get a proper error from ScalaSig along the lines of
```
Exception in thread "main" org.json4s.package$MappingException: Can't find ScalaSig for class org.json4s.LittleBunnyFooFoo$Foo$3
```

Whereas,
```scala
object LittleBunnyFooFoo {
  type ID = Int
  case class Foo(is: List[ID])

  def main(args: Array[String]) {
    val f = Foo(10 :: Nil)

    implicit lazy val formats = DefaultFormats

    println(Extraction.decompose(f).extract[Foo])
  }
}
```
works as expected.

I can get the infinite loop if I add code to the unit tests like this (in this case in ExtractionBugs.scala):
```scala
"Extraction should, definitely, not hang when using a type alias" in {
  type ID = Int
  case class TypeAliasedContained(is: List[ID])
  val f = TypeAliasedContained(10 :: Nil)
  Extraction.decompose(f).extract[TypeAliasedContained] must_== f
}
```
If I move the case class def to the companion object for the ExtractionBugs spec, then it runs fine.

So there is a strange bug with infinite recursion in the `findPrimitive` function in ScalaSigReader, however most folks could probably get around this by making sure that their case classes are not defined inside some nested structure, other than simple `object`.

**Comment by casualjim** [comment] 2015-02-12 05:20
thank you @jeffdc, that's exactly what the readme says too. Only top level objects are supported. I'm closing this as by design. 

then @nefilim json4s as been an effort I spent lots of my free time on. If you want something fixed, before another **volunteer** gets to it, fix it and send a pull request. Outrage is not appropriate here.

**Closed by casualjim** 2015-02-12 05:20 UTC

**Comment by meirmaor** [comment] 2015-12-14 09:07
@casualjim I am not very familiar with this codepath but couldn't we just remove the offending line:
      case ref @ TypeRefType(_, _, _) => findPrimitive(ref)

https://github.com/json4s/json4s/blob/3.4/core/src/main/scala/org/json4s/reflect/ScalaSigReader.scala#L147

and cause a failure instead of an infinite loop? 
not a fix, but seems to me like a great improvement.

**Comment by dsbos** [comment] 2016-08-13 16:08
#397 seems relaated.
