### ISSUE TITLE
Can't find ScalaSig for xxx.xxx.xxx

### ISSUE THREAD

**Issue by Liyw979** [json4s/json4s#1285] opened 2023-05-11 10:06 UTC
### json4s version
4.0.6
### scala version
3.2.2
### jdk version
17

`Map[String, Int]` causes this error,  and both `Map[String, String]` and `Map[String, Integer]` works fine.
```
case class JsonPathScan(
  amountSummary: Map[String, Int],
) extends Json:
```

**Comment by gregghz** [comment] 2023-05-11 17:23
this is likely a duplicate of https://github.com/json4s/json4s/issues/1035

No real work has been done on that for quite a while :(

**Closed** 2023-05-22 21:48 UTC
