### ISSUE TITLE
Recursion bug in Json4sScalaModule deserialisation logic

### ISSUE THREAD

**Issue by tmoschou** [json4s/json4s#603] opened 2019-05-23 08:01 UTC
There is a recursion bug in the deserialisation logic for Json4sScalaModule.

## Steps to reproduce
```scala
import com.fasterxml.jackson.databind.ObjectMapper
import org.json4s.jackson.Json4sScalaModule
import org.json4s._

val mapper = new ObjectMapper
mapper.registerModule(Json4sScalaModule)

scala> mapper.readValue("""{"x":"y"}""", classOf[JValue])
res1: org.json4s.JValue = JObject(List((x,JString(y))))

scala> mapper.readValue("""{}""", classOf[JObject])
res2: org.json4s.JObject = JObject(List())

scala> mapper.readValue("""{"x":"y"}""", classOf[JObject])
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.json4s.JsonAST$JObject out of VALUE_STRING token
 at [Source: {"x":"y"}; line: 1, column: 2]
  at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
  at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:857)
  at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:853)
  at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:50)
  at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:42)
  at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:35)
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
  ... 55 elided
```

You can see we can deserialise `{"x": "y"}` into a JValue, or an empty `{}` into a JObject, but we cannot deserialise a non empty `{"x": "y"}` into a `JObject` when we recurse and deserialise a value that is not assignable to JObject (i.e `JString("y")`).

### json4s version
3.2.11

### scala version
2.11

### jdk version
1.8

**Comment by magnolia-k** [comment] 2019-06-08 15:28
@tmoschou 

The following code checks whether the generated object can be assigned to the specified class.

https://github.com/json4s/json4s/blob/aafa25b79d48b7b9d77debf0ded4497ba0980414/jackson/src/main/scala/org/json4s/jackson/JValueDeserializer.scala#L53

When JObject or JArray is specified, if an element is generated as JValue, an error occurs because JValue can not be assigned to JObject and JArray.

This check is performed at each recursive call, but it seems that it may be sufficient to perform it only once at the end.

It is possible to fix it, but since there is no merit in specifying anything other than JValue (the current JSON standard does not necessarily become JObject), it seems that this code is not a problem.

**Comment by tmoschou** [comment] 2019-06-11 07:19
> .. but since there is no merit in specifying anything other than JValue (the current JSON standard does not necessarily become JObject), it seems that this code is not a problem.

Im sorry but I don't understand what you mean here. Our use-case is that we are using the Spring Framework and its use of jackson's object mapper. We [customise](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-spring-mvc.html#howto-customize-the-jackson-objectmapper) the Spring Jackson ObjectMapper by registering the `Json4sScalaModule` among `com.fasterxml.jackson.module.scala.DefaultScalaModule` and other things. We do not use the object mapper defined in org.json4s.jackson.JsonMethods nor can we use `JsonMethods.parse()`, since the spring framework handles the deserialisation and its use of ObjectMapper directly. 

We wish to define beans that are target for deserialisation that include JObject. E.g
```
case class Foo(field1: String, field2: JObject, field3: Bar)
```

When Jackson queries if Json4sScalaModule is able to deserialise JObject [here](https://github.com/json4s/json4s/blob/master/jackson/src/main/scala/org/json4s/jackson/JValueDeserializerResolver.scala#L11), it returns a non-null `com.fasterxml.jackson.databind.JsonDeserializer` indicating that it can, but then fails when it actually tries to deserialise as shown above. In my view, the current implementation has a bug because it violates the contract for [com.fasterxml.jackson.databind.deser.Deserializers](https://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/deser/Deserializers.html)

**Comment by magnolia-k** [comment] 2019-06-16 06:21
I finally understood your intended use case. Make a PR to address this issue.

https://github.com/json4s/json4s/pull/605

**Closed** 2019-06-17 22:49 UTC

**Comment by magnolia-k** [comment] 2019-06-17 22:51
@tmoschou 

Now that the PR has been merged, please try not to reproduce it.
